import CartProvider from "@contexts/CartContext"

import '../../styles/globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className="bg-gray-100 text-gray-700 overflow-x-hidden font-sans main min-h-screen">
          <CartProvider>
            <main className="xl:w-1/2 xl:mx-auto py-8">
              {children}
            </main>
          </CartProvider>
        </body>
      </html>
  )
}
